CREATE TABLE [Incomes] ( 
	[IncomeId] INTEGER NOT NULL PRIMARY KEY, 
	[YEAR] INTEGER(4) NOT NULL,
    [MONTH] INTEGER(2) NOT NULL,
    [DAY] INTEGER(2) NOT NULL,
    [SALARY] REAL(50) NOT NULL,
    [NAME] TEXT NOT NULL
);
CREATE TABLE [Expenses] (
    [ExpenseId] INTEGER NOT NULL PRIMARY KEY, 
    [YEAR] INTEGER(4) NOT NULL,
    [MONTH] INTEGER(2) NOT NULL,
    [DAY] INTEGER(2) NOT NULL,
    [NAME] TEXT NOT NULL,
    [CATEGORY] INTEGER(2) NOT NULL,
    [COST] REAL(50) NOT NULL,
    [WAS_PAYED] INTEGER NOT NULL
);