name: Wydatkowoz CI pipeline

on: push

jobs:
  build:
  
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wydatkowoz:latest
  
  test:
    runs-on: ubuntu-20.04
    container:
      image: wydatkowoz:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run tests
      run: ./run_tests.sh

